version: '2.4'

services:
  # PostgreSQL数据库
  postgres:
    image: pgvector/pgvector:pg15  # 使用带pgvector的镜像
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here  # 请修改为实际密码
      POSTGRES_DB: agent_db
    ports:
      - "15432:5432"  # 映射到15432端口，避免与本地PostgreSQL冲突
    volumes:
      - ./docker-data/agent_postgres:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agent_network

networks:
  agent_network:
    name: agent_network

