version: '2.4'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agent_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/agent_postgres:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - agent_network

networks:
  agent_network:
    name: agent_network
