"""add_ai_model_table

Revision ID: cfadc294894e
Revises: 9b893ecd560c
Create Date: 2025-10-04 21:06:33.622564

"""
from typing import Sequence, Union
from uuid import uuid4
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfadc294894e'
down_revision: Union[str, None] = '9b893ecd560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False, comment='模型唯一标识符'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型显示名称'),
    sa.Column('model_id', sa.String(length=100), nullable=False, comment='模型ID'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='模型提供商'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='API基础URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大token数'),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True, comment='是否支持流式输出'),
    sa.Column('supports_tools', sa.Boolean(), nullable=True, comment='是否支持工具调用'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='模型图标URL'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='额外配置，JSON格式'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    # ### end Alembic commands ###

    # 插入初始数据：通义千问3模型
    ai_models_table = sa.table('ai_models',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('model_id', sa.String()),
        sa.column('provider', sa.String()),
        sa.column('base_url', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('max_tokens', sa.Integer()),
        sa.column('supports_streaming', sa.Boolean()),
        sa.column('supports_tools', sa.Boolean()),
        sa.column('is_active', sa.Boolean()),
        sa.column('icon_url', sa.String()),
        sa.column('display_order', sa.Integer()),
        sa.column('config', postgresql.JSON()),
        sa.column('created_at', sa.DateTime()),
        sa.column('updated_at', sa.DateTime()),
    )

    op.bulk_insert(ai_models_table, [
        {
            'id': uuid4(),
            'name': '通义千问3',
            'model_id': 'qwen3:8b',
            'provider': 'ollama',
            'base_url': 'http://localhost:11434',
            'description': '阿里巴巴通义千问3模型，8B参数版本，支持工具调用和函数调用',
            'max_tokens': 8192,
            'supports_streaming': True,
            'supports_tools': True,
            'is_active': True,
            'icon_url': 'https://img.alicdn.com/imgextra/i4/O1CN01lAlxMo1LOs0lFrZG7_!!6000000001290-55-tps-33-53.svg',
            'display_order': 1,
            'config': {'temperature': 0.7, 'top_p': 0.9},
            'created_at': datetime.utcnow(),
            'updated_at': datetime.utcnow(),
        }
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_models')
    # ### end Alembic commands ###

