"""Complete MySQL migration with all tables

Revision ID: f9405fbfc7c1
Revises:
Create Date: 2025-10-09 19:17:39.883241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9405fbfc7c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_invocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='调用记录主键ID'),
    sa.Column('message_id', sa.String(length=36), nullable=False, comment='关联的消息业务ID'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联的会话业务ID'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='第几次LLM调用'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='输入token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='输出token数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总token数'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='调用耗时（毫秒）'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='模型名称'),
    sa.Column('finish_reason', sa.String(length=50), nullable=True, comment='完成原因'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_invocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='调用记录主键ID'),
    sa.Column('message_id', sa.String(length=36), nullable=False, comment='关联的消息业务ID'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联的会话业务ID'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='第几次工具调用'),
    sa.Column('triggered_by_llm_sequence', sa.Integer(), nullable=True, comment='由第几次LLM调用触发'),
    sa.Column('tool_name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('arguments', sa.JSON(), nullable=True, comment='输入参数'),
    sa.Column('result', sa.Text(), nullable=True, comment='执行结果'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='执行状态'),
    sa.Column('cache_hit', sa.Boolean(), nullable=False, comment='是否命中缓存'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_invocations')
    op.drop_table('model_invocations')
    # ### end Alembic commands ###

